{% set name = "optiland" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optiland-{{ version }}.tar.gz
  sha256: d3c8d0a81c954d127c5fd0b0381df398f9a8f412040b62f94ec881adbe0de86c

build:
  entry_points:
    - optiland = optiland_gui.run_gui:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base
    - vtk
    - tabulate
    - numba
    - requests
    - seaborn
    - typing-extensions >=4.13.2
    - PySide6
    - qtconsole

test:
  imports:
    - optiland
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/HarrisonKramer/optiland
  summary: Open Source Optical Design in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://optiland.readthedocs.io/
  dev_url: https://github.com/HarrisonKramer/optiland

extra:
  recipe-maintainers:
    - crnh
    - HarrisonKramer
